export const GET_RECIPES_LOADING = 'GET_RECIPES_LOADING';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAIL = 'GET_RECIPES_FAIL';
export const GET_RECIPE_DETAILS_SUCCESS = 'GET_RECIPE_DETAILS_SUCCESS';
